//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeDemoCURD
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpDetail
    {
        public int EmpId { get; set; }
        public string EmpName { get; set; }
        public string EmpAdress { get; set; }
        public string PhoneNo { get; set; }
        public string Salary { get; set; }
    }
}
